FROM	python:3

RUN	cd /tmp \
&&	wget https://github.com/lh3/minimap2/releases/download/v2.17/minimap2-2.17_x64-linux.tar.bz2 \
&&	tar xf minimap2-2.17_x64-linux.tar.bz2 \
&&	cp minimap2-2.17_x64-linux/minimap2 /usr/local/bin \
&&	cp minimap2-2.17_x64-linux/k8 /usr/local/bin \
&&	cp minimap2-2.17_x64-linux/paftools.js /usr/local/bin \
&&	cd /tmp \
&&	wget https://github.com/malonge/RaGOO/archive/v1.11.tar.gz \
&&	tar xf v1.11.tar.gz \
&&	cd RaGOO-1.11 \
&&	python setup.py install \
&&	cd / \
&&	rm -rf /tmp/* 

LABEL	tool=ragoo version=1.11

WORKDIR	/data
