FROM	ubuntu:18.04

RUN	apt-get update \
&&	apt-get -y install wget \
&&	cd /tmp \
&&	wget https://github.com/lh3/minimap2/releases/download/v2.17/minimap2-2.17_x64-linux.tar.bz2 \
&&	tar xf minimap2-2.17_x64-linux.tar.bz2 \
&&	cp minimap2-2.17_x64-linux/minimap2 /usr/local/bin \
&&	cp minimap2-2.17_x64-linux/k8 /usr/local/bin \
&&	cp minimap2-2.17_x64-linux/paftools.js /usr/local/bin \
&&	cd / \
&&	rm -rf /tmp/* \
&&	apt-get autoremove -y wget \
&&	rm -rf /var/lib/apt/lists/*

LABEL	tool=minimap2 version=2.17

WORKDIR	/data
