FROM 	ubuntu:18.04

RUN	cd /tmp \
&&	apt-get update \
&&	apt-get -y install wget build-essential zlib1g-dev \
&&	wget https://github.com/jstjohn/SeqPrep/archive/v1.2.tar.gz \
&&	tar xf v1.2.tar.gz \
&&	cd SeqPrep-1.2 \
&&	make \
&&	cp SeqPrep /usr/local/bin \
&&	cd / \
&&	apt-get -y autoremove wget build-essential zlib1g-dev \ 
&&	rm -rf /tmp/* 

LABEL	tool=seqprep version=1.2

WORKDIR	/data
