FROM    ncbi/blast:2.9.0

RUN	cd /tmp \
&&	apt-get update \
&&	apt-get install -y libdbi-perl libdbd-mysql-perl libdbd-sqlite3-perl sqlite3 mcl \
&&	apt-get install -y git \
&&	git clone https://github.com/stajichlab/OrthoMCL.git \
&&	cd OrthoMCL \
&&	cp -r bin/* /usr/local/bin/ \
&&	cp -r lib/* /usr/local/lib/ \
&&	cd / \
&&	apt-get autoremove -y git \
&&	rm -rf /var/lib/apt/lists \
&&	rm -rf /tmp/* 

LABEL   tool=orthomcl version=2.0.9

WORKDIR /data
