FROM	alpine:3

RUN   wget https://github.com/genetics-statistics/GEMMA/releases/download/0.98.1/gemma-0.98.1-linux-static.gz \
&&    gzip -d gemma-0.98.1-linux-static.gz \
&&    mv gemma-0.98.1-linux-static /usr/local/bin/gemma \
&&    chmod +x /usr/local/bin/gemma

LABEL	tool=gemma version=0.98.1

WORKDIR	/data
