FROM 	  ubuntu

RUN     apt-get update \
&&      apt-get install -y perl python \
&&      apt-get install -y wget unzip \
&&      cd /tmp \
&&      wget https://github.com/BenLangmead/bowtie2/releases/download/v2.3.5.1/bowtie2-2.3.5.1-linux-x86_64.zip \
&&      unzip bowtie2-2.3.5.1-linux-x86_64.zip \
&&      cp bowtie2-2.3.5.1-linux-x86_64/bowtie2* /usr/local/bin/ \
&&      cd / \
&&      rm -rf /tmp/* \
&&      apt-get autoremove -y wget \
&&      rm -rf /var/lib/apt/lists/*

LABEL	  tool=bowtie2 version=2.3.5.1

WORKDIR /data
