FROM    ubuntu

RUN     cd /tmp \
&&      apt-get update \
&&      apt-get install -y wget \
&&      wget https://ftp.ncbi.nlm.nih.gov/blast/executables/blast+/2.7.1/ncbi-blast-2.7.1+-x64-linux.tar.gz \
&&      tar xf ncbi-blast-2.7.1+-x64-linux.tar.gz \
&&      cp -r ncbi-blast-2.7.1+/bin/* /usr/local/bin/ \
&&      cd / \
&&      apt-get autoremove -y wget
&&      rm -rf /tmp/* \
&&      rm -rf /var/lib/apt/lists/*

LABEL   tool=blast+ version=2.7.1

WORKDIR /data

