FROM    broadinstitute/picard:2.21.4

RUN     echo '#!/usr/bin/env bash' > /usr/local/bin/picard \
&&      echo 'java -jar /usr/picard/picard.jar $*' >> /usr/local/bin/picard \
&&      chmod +x /usr/local/bin/picard

LABEL   tool=picard version=2.21.4

WORKDIR /data
