FROM 	alpine

RUN	apk add perl openjdk11 gnuplot \
&&	cd /tmp \
&&	wget https://github.com/marbl/canu/releases/download/v2.1.1/canu-2.1.1.Linux-amd64.tar.xz \
&&	tar xf canu-2.1.1.Linux-amd64.tar.xz \
&&	cd canu-2.1.1 \
&&	cp -r Linux-amd64/bin/* /usr/local/bin/ \
&&	cp -r Linux-amd64/lib/*	/usr/local/lib/ \
&&	cp -r Linux-amd64/share/* /usr/local/share/ \
&&	cd / \
&&	rm -rf /tmp/*

LABEL	tool=canu version=2.1.1

WORKDIR	/data
