FROM 	alpine

RUN     apk add build-base ncurses-dev zlib-dev bzip2-dev xz-dev \
&&      cd /tmp \
&&      wget https://github.com/samtools/samtools/releases/download/1.9/samtools-1.9.tar.bz2 \
&&      tar xf samtools-1.9.tar.bz2 \
&&      cd samtools-1.9 \
&&      ./configure \
&&      make \
&&      make install \
&&      cd / \
&&      rm -rf /tmp/* \
&&      apk del build-base ncurses-dev zlib-dev bzip2-dev xz-dev

LABEL	tool=samtools version=1.9

WORKDIR	/data
