FROM    ubuntu:18.04

RUN     apt-get update \
&&      apt-get install -y python \
&&      apt-get install -y wget \
&&      cd /tmp \
&&      wget http://cole-trapnell-lab.github.io/cufflinks/assets/downloads/cufflinks-2.2.1.Linux_x86_64.tar.gz \
&&      tar xf cufflinks-2.2.1.Linux_x86_64.tar.gz \
&&      cd cufflinks-2.2.1.Linux_x86_64 \
&&      cp cuffcompare cuffdiff cufflinks cuffmerge cuffnorm cuffquant gffread gtf_to_sam /usr/local/bin/ \
&&      cd / \
&&      apt autoremove -y wget \
&&      rm -rf /tmp/* \
&&      rm -rf /var/lib/apt/list/*

LABEL	  tool=cufflinks version=2.2.1

WORKDIR /data
