FROM	ubuntu

RUN	cd /tmp \
&&	apt-get update \
&&	apt-get install -y wget autoconf gcc \
&&	apt-get install -y zlib1g-dev libbz2-dev liblzma-dev \
&&	apt-get install -y make \
&&	wget https://github.com/samtools/htslib/releases/download/1.9/htslib-1.9.tar.bz2 \
&&	tar xf htslib-1.9.tar.bz2 \
&&	cd htslib-1.9 \
&&	autoheader \
&&	autoconf \
&&	./configure \
&&	make \
&&	make install \
&&	cd / \
&&	apt autoremove -y wget autoconf gcc \
&&	apt autoremove -y zlib1g-dev libbz2-dev liblzma-dev \
&&	rm -rf /var/lib/apt/list/*

RUN	cd /tmp \
&&	apt-get update \
&&	apt-get install -y wget autoconf gcc \
&&	apt-get install -y zlib1g-dev libbz2-dev liblzma-dev \
&&	apt-get install -y make \
&&	wget https://github.com/samtools/bcftools/releases/download/1.9/bcftools-1.9.tar.bz2 \
&&	tar xf bcftools-1.9.tar.bz2 \
&&	cd bcftools-1.9 \
&&	autoheader \
&&	autoconf \
&&	./configure \
&&	make \
&&	make install \
&&	cd / \
&&	apt autoremove -y wget autoconf gcc \
&&	apt autoremove -y zlib1g-dev libbz2-dev liblzma-dev \
&&	apt autoremove -y make \
&&	rm -rf rm -rf /var/lib/apt/list/* 

RUN	cd /tmp \
&&	apt-get update \
&&	apt-get install -y wget autoconf gcc \
&&	apt-get install -y libncurses5-dev zlib1g-dev libbz2-dev \
&&	apt-get install -y liblzma-dev make \
&&	wget https://github.com/samtools/samtools/releases/download/1.9/samtools-1.9.tar.bz2 \
&&	tar xf samtools-1.9.tar.bz2 \
&&	cd samtools-1.9 \
&&	autoheader \
&&	autoconf -Wno-syntax \
&&	./configure \
&&	make \
&&	make install \
&&	cd / \
&&	apt autoremove -y wget autoconf gcc \
&&	apt autoremove -y libncurses5-dev zlib1g-dev libbz2-dev \
&&	apt autoremove -y liblzma-dev make \
&&	rm -rf /var/lib/apt/list/*

RUN	cd /tmp \
&&	apt-get update \
&&	apt-get install -y wget make gcc \
&&	apt-get install -y libssl-dev libcurl3-dev g++ \
&&	apt-get install -y libbamtools-dev libboost-all-dev libncurses5-dev \
&&	apt-get install -y libbz2-dev liblzma-dev \
&&	wget https://github.com/Gaius-Augustus/Augustus/archive/3.3.2.tar.gz \
&&	tar xf 3.3.2.tar.gz \
&&	cd /tmp \
&&	mv bcftools-1.9 bcftools \
&&	mv htslib-1.9 htslib \
&&	mv samtools-1.9 samtools \
&&	cd Augustus-3.3.2/auxprogs/bam2wig \
&&	export TOOLDIR="/tmp" \
&&	mkdir /tmp/Augustus-3.3.2/bin \
&&	make \
&&	cd /tmp/Augustus-3.3.2 \
&&	make \
&&	make install \
&&	cd .. \
&&	mv Augustus-3.3.2/ /opt/augustus \
&&	cd / \
&&	apt autoremove -y wget gcc \
&&	apt autoremove -y libssl-dev libcurl3-dev g++ \
&&	apt autoremove -y libbamtools-dev libboost-all-dev libncurses5-dev \
&&	apt autoremove -y make libbz2-dev liblzma-dev \
&&	rm -rf /tmp/* \
&&	rm -rf /var/lib/apt/list/*

LABEL	tool=augustus version=3.3.2

WORKDIR	/data
