FROM    ubuntu

RUN     cd /tmp \
&&      apt-get update \
&&      apt-get install -y wget \
&&      wget https://bintray.com/artifact/download/blahah/generic/transrate-1.0.3-linux-x86_64.tar.gz \
&&      tar xf transrate-1.0.3-linux-x86_64.tar.gz \
&&      mv transrate-1.0.3-linux-x86_64 /opt/transrate \
&&      ln -s /opt/transrate/transrate /usr/local/bin/ \
&&      cd / \
&&      apt-get autoremove -y wget \
&&      rm -rf /tmp/* \
&&      rm -rf /var/lib/apt/lists/*

RUN     cd /tmp \
&&      apt-get update \
&&      apt-get install -y wget \
&&      wget https://github.com/COMBINE-lab/salmon/releases/download/v0.13.1/salmon-0.13.1_linux_x86_64.tar.gz \
&&      tar xf salmon-0.13.1_linux_x86_64.tar.gz \
&&      cd salmon-latest_linux_x86_64 \
&&      cp bin/* /usr/local/bin/ \
&&      cp lib/* /usr/local/lib/ \
&&      cd / \
&&      rm -rf /tmp/* \
&&      apt-get autoremove -y wget \
&&      rm -rf /var/lib/apt/lists/*

LABEL tool=transrate version=1.0.3

WORKDIR /data
