FROM 	  alpine

RUN	    apk add libbz2 xz-libs libcurl \
&&      apk add build-base zlib-dev bzip2-dev xz-dev curl-dev \
&&      cd /tmp \
&&      wget https://github.com/samtools/htslib/releases/download/1.9/htslib-1.9.tar.bz2 \
&&      tar xf htslib-1.9.tar.bz2 \
&&      cd htslib-1.9 \
&&      ./configure \
&&      make \
&&      make install \
&&      cd / \
&&      rm -rf /tmp/* \
&&      apk del build-base zlib-dev bzip2-dev xz-dev curl-dev

LABEL	tool=htslib version=1.9

WORKDIR	/data
