FROM	ubuntu

RUN	cd /tmp \
&&	apt-get update \
&&	apt-get install -y wget \
&&	wget http://ccb.jhu.edu/software/stringtie/dl/stringtie-1.3.6.Linux_x86_64.tar.gz \
&&	tar xf stringtie-1.3.6.Linux_x86_64.tar.gz \
&&	cp stringtie-1.3.6.Linux_x86_64/stringtie /usr/local/bin/ \
&&	cd / \
&&	apt autoremove -y wget \
&&	rm -rf /tmp/* \
&&	rm -rf /var/lib/apt/list/*

LABEL	tool=stringtie version=1.3.6

WORKDIR /data
