FROM    alpine

RUN     apk add zlib libgomp libstdc++ \
&&      apk add build-base zlib-dev \
&&      cd /tmp \
&&      wget https://github.com/weizhongli/cdhit/releases/download/V4.8.1/cd-hit-v4.8.1-2019-0228.tar.gz \
&&      tar xf cd-hit-v4.8.1-2019-0228.tar.gz \
&&      cd cd-hit-v4.8.1-2019-0228 \
&&      make MAX_SEQ=10000000 \
&&      make install \
&&      cd cd-hit-auxtools \
&&      make MAX_SEQ=10000000 \
&&      cp cd-hit-dup cd-hit-lap read-linker /usr/local/bin \
&&      cd / \
&&      rm -rf /tmp/* \
&&      apk del build-base zlib-dev

LABEL	tool=cdhit version=4.8.1

WORKDIR	/data
