FROM    ubuntu

RUN     apt-get update \
&&      apt-get install -y wget build-essential zlib1g-dev libgomp1 \
&&      cd /tmp \
&&      wget http://catchenlab.life.illinois.edu/stacks/source/stacks-2.41.tar.gz \
&&      tar xf stacks-2.41.tar.gz \
&&      cd stacks-2.41 \
&&      ./configure \
&&      make \
&&      make install \
&&      cd / \
&&      apt-get autoremove -y wget build-essential zlib1g-dev\
&&      rm -rf /tmp/* \
&&      rm -rf /var/lib/apt/lists/*

LABEL tool=stacks version=2.41

WORKDIR /data
