FROM	alpine

RUN	apk add build-base libstdc++ \
&&	cd /tmp \
&&	wget http://trimal.cgenomics.org/_media/trimal.v1.2rev59.tar.gz \
&&	tar xf trimal.v1.2rev59.tar.gz \
&&	cd trimAl/source \
&&	make \
&&	cp readal trimal /usr/local/bin \
&&	cd / \
&&	rm -rf /tmp/* \
&&	apk del build-base

WORKDIR	/data
