FROM 	  ubuntu

RUN     apt-get update \
&&      apt-get install -y build-essential wget libncurses5-dev zlib1g-dev libbz2-dev liblzma-dev \
&&      cd /tmp \
&&      wget https://github.com/samtools/samtools/releases/download/1.9/samtools-1.9.tar.bz2 \
&&      tar xf samtools-1.9.tar.bz2 \
&&      cd samtools-1.9 \
&&      ./configure \
&&      make -j \
&&      make install \
&&      cd / \
&&      apt-get autoremove -y build-essential wget libncurses5-dev zlib1g-dev libbz2-dev liblzma-dev \
&&      rm -rf /tmp/* \
&&      rm -rf /var/lib/apt/lists/*

RUN     apt-get update \
&&      apt-get install -y wget \
&&      wget https://github.com/gmarcais/Jellyfish/releases/download/v2.2.10/jellyfish-linux \
&&      chmod +x jellyfish-linux \
&&      mv jellyfish-linux /usr/local/bin/jellyfish \
&&      apt-get autoremove -y wget \
&&      rm -rf /var/lib/apt/lists/*

RUN     apt-get update \
&&      apt-get install -y perl python \
&&      apt-get install -y wget unzip \
&&      cd /tmp \
&&      wget https://github.com/BenLangmead/bowtie2/releases/download/v2.3.5.1/bowtie2-2.3.5.1-linux-x86_64.zip \
&&      unzip bowtie2-2.3.5.1-linux-x86_64.zip \
&&      cp bowtie2-2.3.5.1-linux-x86_64/bowtie2* /usr/local/bin/ \
&&      cd / \
&&      rm -rf /tmp/* \
&&      apt-get autoremove -y wget \
&&      rm -rf /var/lib/apt/lists/*

RUN     apt-get update \
&&      apt-get install -y wget \
&&      cd /tmp \
&&      wget https://github.com/COMBINE-lab/salmon/releases/download/v0.13.1/salmon-0.13.1_linux_x86_64.tar.gz \
&&      tar xf salmon-0.13.1_linux_x86_64.tar.gz \
&&      cd salmon-latest_linux_x86_64 \
&&      cp bin/* /usr/local/bin/ \
&&      cp lib/* /usr/local/lib/ \
&&      cd / \
&&      rm -rf /tmp/* \
&&      apt-get autoremove -y wget \
&&      rm -rf /var/lib/apt/lists/*

RUN     apt-get update \
&&      apt-get install -y wget \
&&      wget http://hgdownload.soe.ucsc.edu/admin/exe/linux.x86_64/blat/blat \
&&      chmod +x blat \
&&      mv blat /usr/local/bin \
&&      apt-get autoremove -y wget \
&&      rm -rf /var/lib/apt/lists/*

RUN     apt-get update \
&&      apt-get install -y openjdk-8-jre-headless perl python-numpy \
&&      apt-get install -y wget build-essential cmake zlib1g-dev \
&&      mkdir -p /opt \
&&      cd /opt \
&&      wget https://github.com/trinityrnaseq/trinityrnaseq/archive/Trinity-v2.8.4.tar.gz \
&&      tar xf Trinity-v2.8.4.tar.gz \
&&      cd trinityrnaseq-Trinity-v2.8.4 \
&&      make -j \
&&      make plugins \
&&      cd / \
&&      ln -s /opt/trinityrnaseq-Trinity-v2.8.4/Trinity /usr/local/bin/Trinity \
&&      apt-get autoremove -y wget build-essential cmake zlib1g-dev \
&&      rm -rf /var/lib/apt/lists/*

ENV     TRINITY_HOME /opt/trinityrnaseq-Trinity-v2.8.4

LABEL	  tool=trinity version=2.8.4

WORKDIR /data
