FROM    ubuntu:18.40

RUN	cd /tmp \
&&	apt-get update \
&&	apt-get install -y python \
&&	apt-get install -y wget \
&&	wget http://cab.spbu.ru/files/release3.12.0/SPAdes-3.12.0-Linux.tar.gz \
&&	tar -xzf SPAdes-3.12.0-Linux.tar.gz \
&&	cp -r SPAdes-3.12.0-Linux/bin/* /usr/local/bin \
&&	cp -r SPAdes-3.12.0-Linux/share/* /usr/local/share \
&&	cd / \
&&	apt autoremove -y wget \
&&	rm -rf /tmp/* \
&&	rm -rf /var/lib/apt/lists/*

LABEL tool=SPAdes version=3.12.0

WORKDIR /data
