FROM	ubuntu:18.04

RUN     cd /tmp \
&&      apt-get update \
&&      apt-get install -y wget \
&&      wget https://ftp.ncbi.nlm.nih.gov/blast/executables/blast+/2.9.0/ncbi-blast-2.9.0+-x64-linux.tar.gz \
&&      tar xf ncbi-blast-2.9.0+-x64-linux.tar.gz \
&&      cp -r ncbi-blast-2.9.0+/bin/* /usr/local/bin/ \
&&      cd / \
&&      apt-get autoremove -y wget \
&&      rm -rf /tmp/* \
&&      rm -rf /var/lib/apt/lists/*

RUN	apk add bash perl libstdc++ rsync libgomp \
&&	apk add build-base \
&&	cd /tmp \
&&	wget https://github.com/DerrickWood/kraken2/archive/v2.0.7-beta.tar.gz \
&&	tar xf v2.0.7-beta.tar.gz \
&&	cd kraken2-2.0.7-beta \
&&	mkdir -p /opt/kraken2 \
&&	./install_kraken2.sh /opt/kraken2 \
&&	ln -s /opt/kraken2/kraken2 /usr/local/bin/kraken2 \
&&	ln -s /opt/kraken2/kraken2-build /usr/local/bin/kraken2-build \
&&	ln -s /opt/kraken2/kraken2-inspect /usr/local/bin/kraken2-inspect \
&&	cd / \
&&	rm -rf /tmp/* \
&&	apk del build-base

LABEL	tool=kraken2 version=2.0.7-beta

WORKDIR	/data
