FROM 	alpine

RUN	apk add build-base zlib-dev \
&&	cd /tmp \
&&	wget https://github.com/lh3/bwa/releases/download/v0.7.17/bwa-0.7.17.tar.bz2 \
&&	tar xf bwa-0.7.17.tar.bz2 \
&&	cd bwa-0.7.17 \
&&	make \
&&	cp bwa /usr/local/bin/bwa \
&&	cd / \
&&	rm -rf /tmp/* \
&&	apk del build-base zlib-dev

LABEL	tool=bwa version=0.7.17

WORKDIR	/data
