FROM	ubuntu

RUN	cd /tmp \
&&	apt-get update \
&&	apt-get install -y openjdk-11-jre-headless \
&&	apt-get install -y wget build-essential\
&&	wget https://github.com/chgibb/FastQC0.11.5/releases/download/v0.11.5/FastQC.tar.gz \
&&	tar xf FastQC.tar.gz  \
&&	cd FastQC \
&&	chmod 755 fastqc \
&&	cd .. \
&&	mv FastQC /opt/fastqc \
&&	ln -s /opt/fastqc/fastqc /usr/local/bin \
&&	cd / \
&&	apt autoremove -y wget \
&&	rm -rf /tmp/* \
&&	rm -rf /var/lib/apt/list/*

LABEL	tool=fastqc version=0.11.5

WORKDIR /data
