FROM	ubuntu:18.04

RUN	cd /tmp \
&&	apt-get update \
&&	apt-get install -y git ruby curl gcc make \
&&	git clone https://github.com/Homebrew/brew ~/.linuxbrew/Homebrew \
&&	mkdir ~/.linuxbrew/bin \
&&	ln -s ~/.linuxbrew/Homebrew/bin/brew ~/.linuxbrew/bin \
&&	~/.linuxbrew/bin/brew shellenv \
&&	~/.linuxbrew/bin/brew install boost open-mpi google-sparsehash \
&&	apt-get install -y abyss \
&&	cd / \
&&	rm -rf /tmp/* \
&&	rm -rf /var/lib/apt/lists/*

LABEL	tool=abyss version=2.1.5

WORKDIR /data
