FROM	ubuntu:18.04

RUN	apt-get update \
&&	apt-get -y install wget \
&&	cd /tmp \
&&	wget https://github.com/CSB5/lofreq/raw/master/dist/lofreq_star-2.1.3.1_linux-x86-64.tgz \
&&  tar xf lofreq_star-2.1.3.1_linux-x86-64.tgz \
&&	cd lofreq_star-2.1.3.1 \
&&	cp bin/lofreq /usr/local/bin/ \
&&	cp bin/lofreq2_call_pparallel.py /usr/local/bin/ \
&&	cp bin/lofreq2_somatic.py /usr/local/bin/ \
&&  cd / \
&&  apt-get -y autoremove wget \
&&  rm -rf /tmp/* \
&&  rm -rf /var/lib/apt/lists/*

LABEL	tool=lofreq version=2.1.3.1

WORKDIR	/data
